---
listen:
  host: localhost
  port: 55759
mysql:
  db: pal5q
  host: localhost
  port: 3306
  user: pal5q
  pass: DJzwQCjJAeC5JUYVhLpc
redis:
  host: localhost
  port: 6379
  db: 9
  pass: 3D6kiP36dYTK9X2a
logfile: pal5q.log
