drop table if exists`skill`;
CREATE TABLE `skill` (
 `id` smallint(4) unsigned NOT NULL COMMENT '编号',
 `ef` smallint(4) unsigned NOT NULL COMMENT '特效id',
 `icon` smallint(4) unsigned NOT NULL COMMENT '图标id',
 `script` smallint(4) unsigned NOT NULL COMMENT '脚本id',
  `name` varchar(16) NOT NULL COMMENT '名称',
  `description` varchar(48) NOT NULL COMMENT '描述',
 `type` tinyint(1) unsigned NOT NULL COMMENT '类型',
 `loc` tinyint(1) unsigned NOT NULL COMMENT '位置',
 `attr` tinyint(1) unsigned NOT NULL COMMENT '属性',
 `fend` tinyint(1) unsigned NOT NULL COMMENT '击退',
 `short_perm` tinyint(1) unsigned NOT NULL COMMENT '快捷许可',
 `prof_req` smallint(4) unsigned NOT NULL COMMENT '修为要求',
 `trump_req` tinyint(1) unsigned NOT NULL COMMENT '法宝需求',
 `cond_stat` tinyint(2) unsigned NOT NULL COMMENT '条件状态',
 `role` smallint(3) unsigned NOT NULL COMMENT '角色',
 `env_ef` tinyint(1) unsigned NOT NULL COMMENT '环境影响',
 `mp` tinyint(3) unsigned NOT NULL COMMENT 'mp',
 `summon` tinyint(1) unsigned NOT NULL COMMENT '召唤值',
 `fight_will` tinyint(2) unsigned NOT NULL COMMENT '斗志',
 `power` float NOT NULL COMMENT '威力',
 `object` tinyint(1) unsigned NOT NULL COMMENT '对象',
 `party` tinyint(1) unsigned NOT NULL COMMENT '敌我',
 `renew` tinyint(1) unsigned NOT NULL COMMENT '回气',
 `to_air` tinyint(1) unsigned NOT NULL COMMENT '对飞行',
 `usage` tinyint(2) unsigned NOT NULL COMMENT '使用方式',
 `use_perm` tinyint(2) unsigned NOT NULL COMMENT '使用许可',
 `revive` tinyint(1) unsigned NOT NULL COMMENT '复活',
 `comment` varchar(8) NOT NULL COMMENT '备注',
 PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='技能表';