drop table if exists `accouterment`;
CREATE TABLE `accouterment` (
 `id` smallint(4) unsigned NOT NULL COMMENT '编号',
 `name` varchar(8) NOT NULL COMMENT '名称',
 `icon` smallint(4) unsigned NOT NULL COMMENT '图示id',
 `role` smallint(4) unsigned NOT NULL COMMENT '角色',
 `description` varchar(40) NOT NULL COMMENT '描述',
 `property` varchar(8) NOT NULL COMMENT '作用',
 `physical_attack` tinyint(2) unsigned NOT NULL COMMENT '物攻',
 `magic_attack` tinyint(2) unsigned NOT NULL COMMENT '仙攻',
 `physical_defense` tinyint(2) unsigned NOT NULL COMMENT '防御',
 `magic_defense` tinyint(2) unsigned NOT NULL COMMENT '仙防',
 `lucky` tinyint(2) unsigned NOT NULL COMMENT '运势',
 `hitting` tinyint(1) unsigned NOT NULL COMMENT '命中',
 `dodge` tinyint(1) unsigned NOT NULL COMMENT '闪避',
 `block` tinyint(1) unsigned NOT NULL COMMENT '招架',
 `price` smallint(4) unsigned NOT NULL COMMENT '价格',
 `freeze_resist` tinyint(2) unsigned NOT NULL COMMENT '冻结抗性',
 `poison_resist` tinyint(2) unsigned NOT NULL COMMENT '中毒抗性',
 `water_resist` tinyint(2) unsigned NOT NULL COMMENT '水抗性',
 `fire_resist` tinyint(2) unsigned NOT NULL COMMENT '火抗性',
 `earth_resist` tinyint(2) unsigned NOT NULL COMMENT '土抗性',
 `air_resist` tinyint(2) unsigned NOT NULL COMMENT '风抗性',
 `thunder_resist` tinyint(2) unsigned NOT NULL COMMENT '雷抗性',
 `yin_resist` tinyint(2) unsigned NOT NULL COMMENT '阴抗性',
 `yang_resist` tinyint(2) unsigned NOT NULL COMMENT '阳抗性',
 `water_add` tinyint(2) unsigned NOT NULL COMMENT '水加成',
 `fire_add` tinyint(2) unsigned NOT NULL COMMENT '火加成',
 `earth_add` tinyint(2) unsigned NOT NULL COMMENT '土加成',
 `air_add` tinyint(2) unsigned NOT NULL COMMENT '风加成',
 `thunder_add` tinyint(2) unsigned NOT NULL COMMENT '雷加成',
 `yin_add` tinyint(2) unsigned NOT NULL COMMENT '阴加成',
 `yang_add` tinyint(2) unsigned NOT NULL COMMENT '阳加成',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='饰品表';